version: "3"
services:
  database:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5432:5432

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application

  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database
volumes:
  pgdata:
