spring:
  profiles: dev
  server:
    port: 8080
    shutdown: graceful
    servlet:
      charset: UTF-8
      enable: ture
      force: ture
  loggin:
    level:
      org.springframework.web:info

  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      connection-init-sql: SET TIME ZONE 'UTC'
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    platform: postgres
    data: classpath*:database/develop/data.sql
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
    show-sql: true

jwt:
  secret: "12345678901234567890123456789010"
