create table if not exists role
(
    id bigint generated by default as identity
    constraint role_pkey
    primary key,
    role varchar(255),
    user_id bigint
    );

alter table role owner to postgres;

create table if not exists "user"
(
    id bigint generated by default as identity
    constraint user_pkey
    primary key,
    created_at timestamp,
    update_at timestamp,
    address varchar(255),
    birth_date date,
    deleted boolean not null,
    email varchar(255),
    gender varchar(255),
    name varchar(255),
    password varchar(255),
    phone_number varchar(255)
    );

alter table "user" owner to postgres;

create table if not exists product
(
    id bigint generated by default as identity
    constraint product_pkey
    primary key,
    created_at timestamp,
    update_at timestamp,
    brand varchar(255),
    category varchar(255),
    currency varchar(255),
    description varchar(255),
    name varchar(255),
    price varchar(255),
    user_id bigint
    constraint fk979liw4xk18ncpl87u4tygx2u
    references "user"
    );

alter table product owner to postgres;

create table if not exists product_image_link
(
    product_id bigint not null
    constraint fk73ess6oitct2ob9wo5n0x35pe
    references product,
    image_link varchar(255)
    );

alter table product_image_link owner to postgres;
